version: 2

updates:
  # Monitor GitHub Actions used in workflow files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Monitor npm packages listed in package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
